---
abstract: 'easily translate Moose code to Moo'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
  - unknown
build_requires:
  Test::Fatal: '0.010'
  Test::More: '0.96'
  Test::Requires: '0.06'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.016, CPAN::Meta::Converter version 2.140640'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-late
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  MooX::late:
    file: lib/MooX/late.pm
    version: '0.015'
  MooX::late::DefinitionContext:
    file: lib/MooX/late.pm
    version: '0.015'
recommends:
  MooX::HandlesVia: '0.001004'
requires:
  Moo: '1.006000'
  Type::Utils: '1.000001'
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/MooX-late/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooX-late
  homepage: https://metacpan.org/release/MooX-late
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tobyink/p5-moox-late.git
version: '0.015'
