---
abstract: 'easily translate Moose code to Moo'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0.010
  Test::More: 0.96
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooX::late
name: MooX-late
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  MooX: 0
  MooX::HandlesVia: 0.001004
requires:
  Moo: 1.003000
  Type::Utils: 0.016
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooX-late
  homepage: https://metacpan.org/release/MooX-late
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-moox-late
version: 0.014
